version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=966104787185.dkr.ecr.us-east-2.amazonaws.com/bluetechlab
      - IMAGE_LATEST_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - IMAGE_TAG="`cat target/maven-archiver/pom.properties | grep version | cut -d'=' -f 2`"
      - echo $IMAGE_TAG
      - docker build -t $REPOSITORY_URI:$IMAGE_LATEST_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_LATEST_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_LATEST_TAG