version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=966104787185.dkr.ecr.us-east-2.amazonaws.com/bluetechlab
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - target/order-1.0.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes